name: Debian Based CI
on:
  push:
    paths:
      - "qbittorrent-nox-static.sh"
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        container_id: [ubuntu]
        container_codename: [focal]
        build_tool_flag: [-c]
        libtorrent_tag: [-lt RC_1_2]
        include:
          - build_tool_flag: -c
            build_tool_name: cmake
          - libtorrent_tag: -lt RC_1_2
            libtorrent_version: RC-1-2
    name: "${{ matrix.container_id }}-${{ matrix.container_codename }}-${{ matrix.libtorrent_version }}-${{ matrix.build_tool_name }}"
    env:
      build_dir: "qbt-build"
      artifact_name: "${{ matrix.container_id }}-${{ matrix.container_codename }}-${{ matrix.libtorrent_version }}-${{ matrix.build_tool_name }}-nox"
    container:
      image: ${{ matrix.container_id }}:${{ matrix.container_codename }}
      env:
        LANG: en_GB.UTF-8
        DEBIAN_FRONTEND: noninteractive
        TZ: Europe/London
    steps:
      - uses: actions/checkout@v2.3.4

      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static -bs-a ${{ matrix.build_tool_flag }}
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static bison
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static gawk
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static glibc
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static zlib
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static iconv
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static icu
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static openssl
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static boost ${{ matrix.build_tool_flag }}
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static libtorrent ${{ matrix.libtorrent_tag }} ${{ matrix.build_tool_flag }}
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static qtbase -i
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static qttools
      - run: bash qbittorrent-nox-static.sh -pr gorrrr/qbittorrent-nox-static qbittorrent ${{ matrix.build_tool_flag }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.build_dir }}/completed/qbittorrent-nox
